import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/lib/react-query/QueryProvider";
import Provider from "@/provider";
import { StoreProvider } from "@/redux/storeProvider";

export const metadata: Metadata = {
  title: "SnapCart ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="w-full min-h-screen bg-gradient-to-b from-green-50 to-white pt-15">
        <QueryProvider>
          <Provider>
            <StoreProvider>
              {children}
            </StoreProvider>
          </Provider>
        </QueryProvider>
      </body>
    </html>
  );
}
